# Generated by Django 4.1.7 on 2023-03-26 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_calc', '0003_foodinaday_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodInADayId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_calc.foodinaday')),
            ],
        ),
    ]
