# Generated by Django 4.1.7 on 2023-03-26 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_calc', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
