# Generated by Django 4.1.7 on 2023-03-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0002_remove_food_category_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfood',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='userfood',
            name='food',
        ),
        migrations.AddField(
            model_name='userfood',
            name='customer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='calorie.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfood',
            name='food',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='calorie.food'),
            preserve_default=False,
        ),
    ]
